#!/bin/bash

source $(dirname $0)/panel_colors

WIFI=`ifconfig eno1`
IIP=`ifconfig | grep "192.168" | awk '{print $2}'`

ICON="^i($PANEL_ICON_DIR/wifi_02.xbm)"
#echo "^ca(1, ./popup_wifi)^fg($PANEL_COLOR_ICON)$ICON^ca() ^fg($PANEL_COLOR_TEXT)$WIFI"
echo "^fg($PANEL_COLOR_ICON)$ICON ^fg($PANEL_COLOR_TEXT)$WIFI"
