#!/bin/bash

source $(dirname $0)/panel_colors

AMASTER=`amixer get Master | awk 'END{gsub(/\[|\]|%/,""); print $5}'`

VOLBARUSED=`echo $AMASTER / 2 | bc -l | awk '{print int($1+0.5)}'`

volbar() {
	echo "^fg($PANEL_COLOR_TEXT)^r(${VOLBARUSED}x2)^fg(darkgrey)^r($(( 50 - $VOLBARUSED))x2)"
}

if [ $AMASTER == 0 ] ; then
ICON="spkr_04.xbm"
elif [ $AMASTER -le 50 ] ; then
ICON="spkr_02.xbm"
elif [ $AMASTER -le 100 ] ; then
ICON="spkr_01.xbm"
else
ICON="spkr_04.xbm"
fi

ICON="^i($PANEL_ICON_DIR/$ICON)"
echo "^fg($PANEL_COLOR_ICON)$ICON ^fg($PANEL_COLOR_TEXT)$(volbar)^fg($PANEL_COLOR_TEXT)"
