#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi
PANEL_HEIGHT=14

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

[ -e "$PANEL_FIFO_SECOND" ] && rm "$PANEL_FIFO_SECOND"
mkfifo "$PANEL_FIFO_SECOND"

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
./statusbar > "$PANEL_FIFO_SECOND" &
./statusbar2 > "$PANEL_FIFO" &

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | ./panel_bar | bar &
        ;;
    dzen2)
        . panel_colors FONT_FAMILY='-misc-terminusmodx-medium-r-normal--12-120-72-72-c-60-iso8859-1'
        FONT_SIZE=12
       cat "$PANEL_FIFO" | ./panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -w 600 -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
       cat "$PANEL_FIFO_SECOND" | ./panel_dzen2_right -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -w 2200 -x 370 -dock -ta r -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
	   tint2 -c /home/cpn/.config/tint2/tint2rc-bspwm
       ;;
esac

wait
