#!/bin/bash

source $(dirname $0)/panel/panel_colors

# Visual options
bspc monitor -d Main Web Media Games Steam Skype Other
bspc config split_ratio         0.50
bspc config border_width        1
bspc config top_padding		15
bspc config window_gap 		0
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_cancel true
bspc config window_gap	20
bspc config normal_border_color none
bspc config active_border_color "#746C48"
bspc config focused_border_color "#746C44"
bspc config presel_border_color  "#446C40"
bspc config urgent_border_color "#504339"
bspc desktop ^3 -t floating=on

# Rules
bspc rule -a Thunderbird desktop=Web
bspc rule -a Firefox desktop=Web
bspc rule -a Deluge desktop=Web
bspc rule -a Gw2.exe floating=on desktop=Games
bspc rule -a Wine desktop=Games
bspc rule -a Python2.7 desktop=Games
bspc rule -a Battle.net.exe desktop=Games floating=on
bspc rule -a Hearthstone.exe desktop=Games floating=on
bspc rule -a Diablo\ III.exe desktop=Games floating=on
bspc rule -a Steam desktop=Steam floating=on
bspc rule -a hl2_linux desktop=Steam
bspc rule -a Skype desktop=Skype floating=on
bspc rule -a MPlayer desktop=Media floating=on
bspc rule -a Vlc desktop=Media floating=on
bspc rule -a Pcmanfm floating=on
bspc rule -a \* center=true
if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

# Autostart applications
#mopidy &
#thunderbird &
dropboxd &
(cd ~/.config/bspwm/panel && ./panel dzen2) &
redshiftgui -b 0.9
